package com.azet.KitchenAssistant.dto;

import com.azet.KitchenAssistant.Entity.Category;
import com.azet.KitchenAssistant.Entity.Nutrient;
import com.azet.KitchenAssistant.Entity.Product;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class ProductCreationRequest {

    @NotBlank(message = "Nazwa produktu jest wymagana.")
    private String productName;
    private String productImage;    //route or url generated by AI
    private String codeBar;

    @NotBlank(message = "Nazwa kategorii jest wymagana.")
    private String categoryName;

    @Valid
    @NotNull(message = "Dane odżywcze są wymagane.")
    private Nutrient nutrient;
}
