package com.azet.KitchenAssistant.Entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.Set;


@Entity
@Table(name = "product")
@Getter
@Setter
@ToString(exclude = {"category", "nutrients", "shoppingListItems"})
public class Product {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    private String name;

    private String image;    //route or url generated by AI

    private String codeBar;

    @ManyToOne
    @JoinColumn(name= "category_id")
    private Category category;

    @OneToOne(cascade = CascadeType.ALL, mappedBy = "product")
    private Nutrient nutrients;

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "product")
    @JsonIgnore
    private Set<ShoppingListItem> shoppingListItems;
}
